require("core")

require("plugins")
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.tree')
require('plugins.telescope')
require('plugins.completion')
require('plugins.lsp')
require('plugins.debugging')
require("plugins.autopairs")
require('plugins.treesitter')
require("plugins.gitsigns")
require("plugins.indentline")

require("neovide")
